version: '3.8'

services:
  transcript-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - WEBSHARE_USERNAME=${WEBSHARE_USERNAME}
      - WEBSHARE_PASSWORD=${WEBSHARE_PASSWORD}
      - API_KEYS=${API_KEYS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 