from pydantic import BaseModel, Field


class AgentInput(BaseModel):
    query: str = Field(..., description="The query for the LoreBridge agent.")
    context: str | None = Field(None, description="Optional context for the agent.")


class AgentResponse(BaseModel):
    result: str = Field(
        ..., description="The result generated by the LoreBridge agent."
    )
    agent_actions: list[str] | None = Field(
        None, description="List of actions taken by the agent."
    )
