"""add cascade delete to chat_messages

Revision ID: 0922cff1a8dd
Revises: 21965d4025e9
Create Date: 2025-07-19 19:58:55.614988

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0922cff1a8dd"
down_revision: str | None = "21965d4025e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "chat_messages_chat_session_id_fkey", "chat_messages", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "chat_messages",
        "chat_sessions",
        ["chat_session_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, "chat_messages", type_="foreignkey")
    op.create_foreign_key(
        "chat_messages_chat_session_id_fkey",
        "chat_messages",
        "chat_sessions",
        ["chat_session_id"],
        ["id"],
    )
    # ### end Alembic commands ###
