"""add_not_null_constraints_to_subscription_fields

Revision ID: 21965d4025e9
Revises: a568035c1b96
Create Date: 2025-07-17 22:24:18.711577

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21965d4025e9"
down_revision: str | None = "a568035c1b96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "subscription_status", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users",
        "subscription_cancel_at_period_end",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users", "has_used_trial", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "has_used_trial", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "users",
        "subscription_cancel_at_period_end",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users", "subscription_status", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
