"""add_stripe_subscription_fields_to_user

Revision ID: 249b00780aee
Revises: e00e3cf32588
Create Date: 2025-07-17 14:10:22.732326

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "249b00780aee"
down_revision: str | None = "cdd4c3667539"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("subscription_status", sa.String(), nullable=True))
    op.add_column("users", sa.Column("stripe_customer_id", sa.String(), nullable=True))
    op.add_column("users", sa.Column("subscription_id", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column("subscription_current_period_end", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("subscription_cancel_at_period_end", sa.Boolean(), nullable=True),
    )
    op.add_column("users", sa.Column("trial_end_date", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("has_used_trial", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "has_used_trial")
    op.drop_column("users", "trial_end_date")
    op.drop_column("users", "subscription_cancel_at_period_end")
    op.drop_column("users", "subscription_current_period_end")
    op.drop_column("users", "subscription_id")
    op.drop_column("users", "stripe_customer_id")
    op.drop_column("users", "subscription_status")
    # ### end Alembic commands ###
