"""add_vector_db_fields_to_asset

Revision ID: 3093073350ed
Revises: caa0dd0687ea
Create Date: 2025-07-23 22:06:04.867128

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3093073350ed"
down_revision: str | None = "caa0dd0687ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asset",
        sa.Column(
            "vector_db_collection_id",
            sa.String(),
            nullable=True,
            comment="ChromaDB collection ID for this document",
        ),
    )
    op.add_column(
        "asset",
        sa.Column(
            "chunk_count",
            sa.Integer(),
            nullable=True,
            comment="Number of text chunks created for vectorization",
        ),
    )
    op.add_column(
        "asset",
        sa.Column(
            "processing_metadata",
            sa.JSON(),
            nullable=True,
            comment="Metadata about chunking and vectorization process",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset", "processing_metadata")
    op.drop_column("asset", "chunk_count")
    op.drop_column("asset", "vector_db_collection_id")
    # ### end Alembic commands ###
