"""add source_handle and target_handle to edges

Revision ID: 3ea31480e540
Revises: add_youtube_instagram_enum
Create Date: 2025-07-12 04:56:30.760214

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ea31480e540"
down_revision: str | None = "add_youtube_instagram_enum"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("edges", sa.Column("source_handle", sa.String(), nullable=True))
    op.add_column("edges", sa.Column("target_handle", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("edges", "target_handle")
    op.drop_column("edges", "source_handle")
    # ### end Alembic commands ###
