"""add_emoji_and_description_to_graphs

Revision ID: 43972a1333f6
Revises: c477b9cd6a57
Create Date: 2025-07-28 03:50:30.612074

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43972a1333f6"
down_revision: str | None = "c477b9cd6a57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("graphs", sa.Column("emoji", sa.String(), nullable=True))
    op.add_column("graphs", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("graphs", "description")
    op.drop_column("graphs", "emoji")
    # ### end Alembic commands ###
