"""Add file_path column to Asset model

Revision ID: 5748a7b596c1
Revises: 3093073350ed
Create Date: 2025-07-22 16:17:43.057172

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5748a7b596c1"
down_revision: str | None = "3093073350ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asset",
        sa.Column(
            "file_path",
            sa.String(),
            nullable=True,
            comment="Relative path to stored file in the storage directory",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset", "file_path")
    # ### end Alembic commands ###
