"""initial setup

Revision ID: 58dffec79c8b
Revises:
Create Date: 2025-07-11 03:49:31.574819

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58dffec79c8b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artefacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("current_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("video", "pdf", "audio", name="assettype"),
            nullable=False,
            comment="Type of asset: video, pdf, audio",
        ),
        sa.Column(
            "source",
            sa.String(),
            nullable=False,
            comment="URL or filename of the asset source",
        ),
        sa.Column(
            "status",
            sa.Enum("processing", "completed", "failed", name="assetstatus"),
            nullable=False,
            comment="Processing status",
        ),
        sa.Column(
            "transcript", sa.Text(), nullable=True, comment="Extracted transcript text"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_asset_id"), "asset", ["id"], unique=False)
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model_used", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llm_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("USER", "ASSISTANT", "SYSTEM", name="roleenum"),
            nullable=False,
        ),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("is_request", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_messages_id"), "llm_messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_llm_messages_session_id"), "llm_messages", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_llm_messages_user_id"), "llm_messages", ["user_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clerk_user_id", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("os", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_clerk_user_id"), "users", ["clerk_user_id"], unique=True
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chat_session_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_session_id"],
            ["chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "graphs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("graph_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("content_id", sa.UUID(), nullable=True),
        sa.Column("position_x", sa.Float(), nullable=True),
        sa.Column("position_y", sa.Float(), nullable=True),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["graph_id"], ["graphs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "edges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("graph_id", sa.UUID(), nullable=True),
        sa.Column("source_node_id", sa.UUID(), nullable=True),
        sa.Column("target_node_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["graph_id"],
            ["graphs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_node_id"],
            ["nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_node_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("edges")
    op.drop_table("nodes")
    op.drop_table("graphs")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_clerk_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_llm_messages_user_id"), table_name="llm_messages")
    op.drop_index(op.f("ix_llm_messages_session_id"), table_name="llm_messages")
    op.drop_index(op.f("ix_llm_messages_id"), table_name="llm_messages")
    op.drop_table("llm_messages")
    op.drop_table("chat_sessions")
    op.drop_index(op.f("ix_asset_id"), table_name="asset")
    op.drop_table("asset")
    op.drop_table("artefacts")
    # ### end Alembic commands ###
