"""add context message source

Revision ID: 816775820e80
Revises: 0922cff1a8dd
Create Date: 2025-07-19 20:26:46.612946

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "816775820e80"
down_revision: str | None = "0922cff1a8dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages", sa.Column("source_chat_session_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "chat_messages",
        "chat_sessions",
        ["source_chat_session_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, "chat_messages", type_="foreignkey")
    op.drop_column("chat_messages", "source_chat_session_id")
    # ### end Alembic commands ###
