"""add_subscription_defaults

Revision ID: a568035c1b96
Revises: 249b00780aee
Create Date: 2025-07-17 22:23:18.893040

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a568035c1b96"
down_revision: str | None = "249b00780aee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
