"""add_descriptive_text_to_artefacts

Revision ID: add_descriptive_text_to_artefacts
Revises: caa0dd0687ea
Create Date: 2024-01-14 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_desc_to_artefacts'
down_revision = 'add_proc_fields_artefacts'  # This should be the latest revision
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artefacts', sa.Column('descriptive_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artefacts', 'descriptive_text')
    # ### end Alembic commands ###
