"""add_last_accessed_at_to_graphs

Revision ID: c477b9cd6a57
Revises: ac6a8b575ed6
Create Date: 2025-07-26 17:37:28.231849

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c477b9cd6a57"
down_revision: str | None = "ac6a8b575ed6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("graphs", sa.Column("last_accessed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("graphs", "last_accessed_at")
    # ### end Alembic commands ###
