"""add_favorite_field_to_graphs

Revision ID: caa0dd0687ea
Revises: 816775820e80
Create Date: 2025-07-24 23:42:45.697617

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "caa0dd0687ea"
down_revision: str | None = "816775820e80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("graphs", sa.Column("is_favorite", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("graphs", "is_favorite")
    # ### end Alembic commands ###
