"""add tool_output to chat_message

Revision ID: cdd4c3667539
Revises: 2dba6d7351bd
Create Date: 2025-07-14 21:31:43.007938

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cdd4c3667539"
down_revision: str | None = "2dba6d7351bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages",
        sa.Column("tool_output", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_messages", "tool_output")
    # ### end Alembic commands ###
