"""add website enum

Revision ID: cf51717dd7d1
Revises: 58dffec79c8b
Create Date: 2025-07-11 05:01:44.041490

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "cf51717dd7d1"
down_revision: str | None = "58dffec79c8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
