"""add website enum

Revision ID: e7f2d992db1c
Revises: cf51717dd7d1
Create Date: 2025-07-11 05:04:42.306990

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7f2d992db1c"
down_revision: str | None = "cf51717dd7d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE assettype ADD VALUE 'website';")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
